[WIP] ecommerce Basket Page -> micro-frontend
raccoongang/ecommerce pull request #41
Opened 2022-05-04 16:24 UTC by UvgenGen

https://github.com/openedx/public-engineering/issues/68
[OeX_Depr-158](https://youtrack.raccoongang.com/agiles/104-960/105-2571?issue=OeX_Depr-158) ecommerce Basket Page -> micro-frontend

2022-05-05 08:26 UTC, idegtiarov requested changes
Nits and comment, other LGTM! Please take a look at my comment inline

2022-05-05 08:26 UTC, idegtiarov commented on ecommerce/core/models.py
> +        # TODO: update it
It seems it is a time for updating, since self argument is removed

2022-05-05 08:26 UTC, idegtiarov commented on ecommerce/tests/factories.py
> +    payment_microfrontend_url = 'http://{}.fake/'.format(Faker().domain_name())
nit: I would use f-string instead of format?

2022-05-06 12:58 UTC, idegtiarov approved these changes
LGTM thanks!

2022-05-11 12:43 UTC, dyudyunov commented on ecommerce/core/management/commands/create_or_update_site.py
>          parser.add_argument('--payment-microfrontend-url',
I think this option should be `required=True` now, doesn't it?

2022-05-11 13:19 UTC, UvgenGen commented on ecommerce/core/management/commands/create_or_update_site.py
>          parser.add_argument('--payment-microfrontend-url',
updated)

2022-05-11 15:21 UTC, dyudyunov approved these changes

2022-05-11 15:29 UTC, idegtiarov approved these changes
LGTM

2022-05-12 08:52 UTC, ruzniaievdm approved these changes

2022-05-12 11:01 UTC, closed without merging